### ISSUE TITLE
Lets get this project going!!

### ISSUE THREAD

**Issue by soraiabinz** [OpenDesign-SUPSI/GroupA-1415#1]
Hey guys! How about we get some quick brainstorming going on what to develop as a project!

I feel like developing something to potentially be fabricated with the CNC machine in the final stage... that way we can all create something together and learn how to use the CNC machine together!

Here's an idea, maybe we could create some comfortable chairs and a table to hang out in the lab, so we can make our stays there more 'homey'

Let me know what you all think!!
And please share your ideas and contribute to the brainstorm!

**Comment by frokeneriksen** [comment]
I am up for that...although I think chairs (comfortable ones) might not be the easiest thing to design...also consider the amount of materials needed...But would be good with something actual useful for us:)

**Comment by francesca17** [comment]
Hi i attach here some case studies that can help us with the concept :)
![hidden-furniture-series](https://cloud.githubusercontent.com/assets/9048859/5444033/4f9844e4-84a7-11e4-8643-fe64b6baf621.jpg)
![unusual-dining-room-furniture-cube-table](https://cloud.githubusercontent.com/assets/9048859/5444039/589daea8-84a7-11e4-9ed0-8881443af34f.jpg)
![creative-metal-urban-furniture-chair-design](https://cloud.githubusercontent.com/assets/9048859/5444044/6256ed60-84a7-11e4-9bb5-2b6829625b5a.jpg)

**Comment by francesca17** [comment]
other inspiration ;)

![modular-playful-furniture-arrangements-468x312](https://cloud.githubusercontent.com/assets/9048859/5478104/a57d5ef4-8631-11e4-95e3-0b32d56a62ba.jpg)

![modular-infinite-variety-furniture-468x312](https://cloud.githubusercontent.com/assets/9048859/5478109/af1579e2-8631-11e4-8988-f953dab8e1ee.jpg)

![modular-stacked-furniture-design-468x312](https://cloud.githubusercontent.com/assets/9048859/5478111/b559083c-8631-11e4-85f1-ebb0c26db998.jpg)

**Comment by giuliarouge** [comment]
Hello, I am developing some modular shelves, take a look and modified stuff if you want!

**Comment by francesca17** [comment]
i think we could work and design something like that...
![tool carrier](https://cloud.githubusercontent.com/assets/9048859/5568441/544af0cc-8f5b-11e4-9aff-fcb617be5d9b.jpg)

**Comment by francesca17** [comment]
i think it's easy to design in one day and useful for our lab ;)

**Comment by giuliarouge** [comment]
Hei, do you think we can use some tissues or ropes/ribbons for the chairs?

**Comment by soraiabinz** [comment]
Hey guys, thanks for the ideas!
I think we could potentially do a combination of both ideas... (modular furniture + tool box idea)
We could create simple modular structure that works as shelving and seating as you showed above, but also add some baskets and compartments (including a toolbox) to store our various tools.

for example:

![image](https://cloud.githubusercontent.com/assets/9048838/5598161/15424200-92b1-11e4-9aeb-1abc45e38fba.png)

![image](https://cloud.githubusercontent.com/assets/9048838/5598166/25f931f8-92b1-11e4-9203-56d3e476f647.png)

**Comment by francesca17** [comment]
yes great idea ;)
